export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const ADD_SKILL = "ADD_SKILL";
export const REMOVE_SKILL = "REMOVE_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_WORK = 'UPDATE_WORK'
export const REMOVE_WORK = 'REMOVE_WORK'
export const ADD_WORK = 'ADD_WORK'
export const EDIT_WORK = 'EDIT_WORK'
export const STORE_UNDO ='STORE_UNDO'
export const EXECUTE_UNDO ='EXECUTE_UNDO'